import type { InterfaceLanguage } from "../shared/settings.js";
const en = {
  workspace: "Write",
  history: "History",
  setup: "Local setup",
  settings: "Settings",
  local: "Your words stay here.",
  title: "Make room for your words.",
  subtitle:
    "A writing space for imperfect keyboards. Choose how much help you want.",
  editor: "Your text",
  placeholder: "Start a prompt, draft a post, or get a thought down…",
  profile: "Writing profile",
  prose: "Everyday writing",
  prompt: "AI prompts",
  code: "Code and commands",
  spreadsheet: "Spreadsheet text",
  mode: "AI assistance",
  off: "Off",
  suggest: "Suggest",
  automatic: "Automatic",
  modeHelp:
    "Off leaves your text as you type it. Suggestions need approval. Automatic repair requires a connected local service and a verified editor.",
  protection: "Typing protection",
  sensitivity: "Keyboard sensitivity",
  intensity: "Repair intensity",
  language: "Language",
  interfaceLanguage: "App language",
  repairLanguage: "Repair language",
  detect: "Detect language",
  personal: "Your writing",
  style: "Your style card",
  styleHelp: "Describe how you write. Only guidance you save is used.",
  vocabulary: "Your vocabulary",
  vocabularyHelp: "One name or term per line. Up to 200 entries.",
  keys: "Keyboard shortcuts",
  keysHelp:
    "Use at least two modifiers, for example Control+Alt+D. Changes are checked before registration.",
  dictate: "Toggle dictation",
  repair: "Repair selection",
  read: "Read aloud",
  pause: "Pause protection",
  show: "Show workspace",
  save: "Save preferences",
  saved: "Preferences saved.",
  invalid: "Check levels, vocabulary and shortcut conflicts.",
  unavailable:
    "Local storage is unavailable. Your previous saved choices remain.",
  shortcutError:
    "A shortcut is unavailable. Review Keyboard shortcuts in Settings. Any previous working bindings were restored.",
  status: "Local status",
  foundation: "Workspace ready",
  nativePending: "System-wide typing protection is not connected yet.",
  aiPending: "Local repair is not connected yet.",
  speechPending:
    "Speech setup will appear here when the local provider is connected.",
  characters: "characters",
  words: "words",
  session: "This draft stays in this session.",
  support: "Support FixMyType",
  historyTitle: "Keep the changes that help.",
  historyBody: "There are no committed changes in this session.",
  setupTitle: "Everything runs on your computer.",
  setupBody:
    "Each component reports its own readiness. An installed runtime is not a completed connection.",
  typing: "Typing",
  ai: "Text repair",
  voice: "Speech",
  pending: "Not connected",
  ready: "Ready",
  companion: "Show companion control",
  close: "Back to writing",
  footer: "Free and open source. Built for your keyboard.",
  operationPending:
    "This shortcut is configured. Its local service is not connected yet.",
  reset: "Reset invalid preferences",
} as const;
type Words = { [K in keyof typeof en]: string };
const nl: Words = {
  workspace: "Schrijven",
  history: "Geschiedenis",
  setup: "Lokale installatie",
  settings: "Instellingen",
  local: "Je woorden blijven hier.",
  title: "Geef je woorden de ruimte.",
  subtitle:
    "Een schrijfplek voor een onvolmaakt toetsenbord. Jij bepaalt hoeveel hulp je krijgt.",
  editor: "Je tekst",
  placeholder:
    "Begin een prompt, schrijf een bericht of leg een gedachte vast…",
  profile: "Schrijfprofiel",
  prose: "Gewone tekst",
  prompt: "AI-prompts",
  code: "Code en opdrachten",
  spreadsheet: "Tekst in spreadsheets",
  mode: "AI-hulp",
  off: "Uit",
  suggest: "Voorstellen",
  automatic: "Automatisch",
  modeHelp:
    "Uit laat je tekst staan zoals je typt. Voorstellen wachten op akkoord. Automatisch herstel vereist een verbonden lokale dienst en een geteste editor.",
  protection: "Typbescherming",
  sensitivity: "Toetsenbordgevoeligheid",
  intensity: "Herstelintensiteit",
  language: "Taal",
  interfaceLanguage: "Taal van de app",
  repairLanguage: "Taal voor herstel",
  detect: "Taal herkennen",
  personal: "Jouw schrijfstijl",
  style: "Je stijlkaart",
  styleHelp:
    "Beschrijf hoe je schrijft. Alleen opgeslagen aanwijzingen worden gebruikt.",
  vocabulary: "Je woordenlijst",
  vocabularyHelp: "Eén naam of term per regel. Maximaal 200 woorden.",
  keys: "Sneltoetsen",
  keysHelp:
    "Gebruik minimaal twee speciale toetsen, bijvoorbeeld Control+Alt+D. Wijzigingen worden gecontroleerd.",
  dictate: "Dicteren starten of stoppen",
  repair: "Selectie herstellen",
  read: "Voorlezen",
  pause: "Bescherming pauzeren",
  show: "Schrijfplek openen",
  save: "Voorkeuren opslaan",
  saved: "Voorkeuren opgeslagen.",
  invalid: "Controleer standen, woordenlijst en dubbele sneltoetsen.",
  unavailable:
    "Lokale opslag is niet beschikbaar. Eerder opgeslagen keuzes blijven staan.",
  shortcutError:
    "Een sneltoets is niet beschikbaar. Controleer Sneltoetsen in Instellingen. Eerder werkende toetsen zijn hersteld.",
  status: "Lokale status",
  foundation: "Schrijfplek klaar",
  nativePending: "Typbescherming in andere apps is nog niet verbonden.",
  aiPending: "Lokaal tekstherstel is nog niet verbonden.",
  speechPending:
    "Spraakinstellingen verschijnen hier zodra de lokale dienst is verbonden.",
  characters: "tekens",
  words: "woorden",
  session: "Dit concept blijft in deze sessie.",
  support: "Support FixMyType",
  historyTitle: "Bewaar de veranderingen die helpen.",
  historyBody: "Er zijn nog geen toegepaste wijzigingen in deze sessie.",
  setupTitle: "Alles draait op je computer.",
  setupBody:
    "Elk onderdeel toont zijn eigen status. Een geïnstalleerde dienst is nog geen werkende verbinding.",
  typing: "Typen",
  ai: "Tekstherstel",
  voice: "Spraak",
  pending: "Niet verbonden",
  ready: "Klaar",
  companion: "Companionknop tonen",
  close: "Terug naar schrijven",
  footer: "Gratis en open source. Gebouwd voor jouw toetsenbord.",
  operationPending:
    "Deze sneltoets is ingesteld. De lokale dienst is nog niet verbonden.",
  reset: "Ongeldige voorkeuren resetten",
};
export const wordsFor = (language: InterfaceLanguage): Words =>
  language === "nl" ? nl : en;
export type { Words };
